services:
  postgres:
    image: postgres:15
    container_name: express_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root12345
      POSTGRES_DB: hbs_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: express_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
